apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: diamond0816/myimages:1.0
          env:
            - name: DATABASE_URL
              value: "postgresql://myuser:mypassword@postgresql:5432/mydatabase"
          ports:
            - containerPort: 3000

--- 
apiVersion: v1
kind: Service
metadata:
  name: rails-app
spec:
  selector:
    app: rails-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

